"""empty message

Revision ID: 2105f3d01d0
Revises: 371b149dfd
Create Date: 2015-10-15 21:22:08.045037

"""

# revision identifiers, used by Alembic.
revision = '2105f3d01d0'
down_revision = '371b149dfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprints', 'sprint_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprints', 'sprint_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
