"""empty message

Revision ID: 24f73580841
Revises: 39062722f13
Create Date: 2015-10-21 20:23:01.406056

"""

# revision identifiers, used by Alembic.
revision = '24f73580841'
down_revision = '39062722f13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
