"""empty message

Revision ID: 278d2ef75b2
Revises: 41ed631bdee
Create Date: 2015-10-17 19:54:50.409556

"""

# revision identifiers, used by Alembic.
revision = '278d2ef75b2'
down_revision = '41ed631bdee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('delivery_manager', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('scrum_tool_link', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'scrum_tool_link')
    op.drop_column('projects', 'delivery_manager')
    ### end Alembic commands ###
