"""empty message

Revision ID: 35a1a19beae
Revises: 278d2ef75b2
Create Date: 2015-10-17 21:28:12.949167

"""

# revision identifiers, used by Alembic.
revision = '35a1a19beae'
down_revision = '278d2ef75b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprintpeople',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprintpeoplerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprintpeople_id', sa.Integer(), nullable=False),
    sa.Column('sprint_day', sa.Integer(), nullable=False),
    sa.Column('sprint_daystatus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprintpeoplerecord')
    op.drop_table('sprintpeople')
    ### end Alembic commands ###
