"""empty message

Revision ID: 371b149dfd
Revises: afb7a8a67
Create Date: 2015-10-11 17:55:40.091702

"""

# revision identifiers, used by Alembic.
revision = '371b149dfd'
down_revision = 'afb7a8a67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_description', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_description')
    ### end Alembic commands ###
