"""empty message

Revision ID: 39062722f13
Revises: f0ec4c5f1f
Create Date: 2015-10-21 20:15:42.250026

"""

# revision identifiers, used by Alembic.
revision = '39062722f13'
down_revision = 'f0ec4c5f1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('burndown_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'burndown_type')
    ### end Alembic commands ###
