"""empty message

Revision ID: 3b25dc1cf49
Revises: 40177419fe9
Create Date: 2015-10-21 21:30:52.378311

"""

# revision identifiers, used by Alembic.
revision = '3b25dc1cf49'
down_revision = '40177419fe9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###


    conn = op.get_bind()
    conn.execute(text('alter table "sprints" alter column "end_date" type date using ("end_date"::text::date);'))
    conn.execute(text('alter table "sprints" alter column "start_date" type date using ("start_date"::text::date);'))




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprints', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('sprints', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    ### end Alembic commands ###
