"""empty message

Revision ID: 3ce9dfad5
Revises: 15d38f6b066
Create Date: 2015-10-09 21:09:38.572874

"""

# revision identifiers, used by Alembic.
revision = '3ce9dfad5'
down_revision = '15d38f6b066'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burndown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('sprint_day', sa.Integer(), nullable=False),
    sa.Column('sprint_done', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burndown')
    ### end Alembic commands ###
