"""empty message

Revision ID: afb7a8a67
Revises: 3ce9dfad5
Create Date: 2015-10-09 21:25:58.999078

"""

# revision identifiers, used by Alembic.
revision = 'afb7a8a67'
down_revision = '3ce9dfad5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('sprint_days', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'sprint_days')
    ### end Alembic commands ###
