"""empty message

Revision ID: f0ec4c5f1f
Revises: 37572b469aa
Create Date: 2015-10-18 15:59:33.941809

"""

# revision identifiers, used by Alembic.
revision = 'f0ec4c5f1f'
down_revision = '37572b469aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('sprint_teamdays', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'sprint_teamdays')
    ### end Alembic commands ###
